-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public.projects;

CREATE TABLE IF NOT EXISTS public.projects (
    id integer NOT NULL,
    project_name character varying NOT NULL,
    sales_price_cent integer NOT NULL,
    project_start timestamp with time zone,
    project_end timestamp with time zone,
    closed boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.employees;

CREATE TABLE IF NOT EXISTS public.employees (
    id integer NOT NULL,
    first_name character varying,
    last_name character varying,
    employee_class integer,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.employee_class;

CREATE TABLE IF NOT EXISTS public.employee_class (
    id integer NOT NULL,
    class_name character varying,
    hourly_rate_cent integer,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.time_efforts;

CREATE TABLE IF NOT EXISTS public.time_efforts (
    id integer NOT NULL,
    employee_id integer,
    project_id integer,
    time_spent_min integer,
    datetime timestamp with time zone,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.invest_efforts;

CREATE TABLE IF NOT EXISTS public.invest_efforts (
    id integer NOT NULL,
    project_id integer,
    invest_cent integer,
    description character varying,
    datetime timestamp with time zone,
    PRIMARY KEY (id)
);

ALTER TABLE
    IF EXISTS public.employees
ADD
    FOREIGN KEY (employee_class) REFERENCES public.employee_class (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

ALTER TABLE
    IF EXISTS public.time_efforts
ADD
    FOREIGN KEY (employee_id) REFERENCES public.employees (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

ALTER TABLE
    IF EXISTS public.time_efforts
ADD
    FOREIGN KEY (project_id) REFERENCES public.projects (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

ALTER TABLE
    IF EXISTS public.invest_efforts
ADD
    FOREIGN KEY (project_id) REFERENCES public.projects (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION NOT VALID;

END;